<<template>
    <div>
        <div>div盒子</div>
        <h1>一级标题</h1>
        <h2>二级标题</h2>
        <p>段落p</p>
        <ul>
            <li>列表</li>
            <li>列表</li>
            <li>列表</li>
        </ul>
        <ol>
            <li>首先</li>
            <li>接着</li>
            <li>最终</li>
        </ol>
    </div>
</template>