
name: GitHub Actions Build and Deploy Blog
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && docs:build